1 D array

In [1]:
import numpy as np

# 1
arr = np.arange(1, 21)

# 2
print(arr[0])

# 3
print(arr[-1])

# 4
print(arr[7])

# 5
arr[4] = 100

# 6
print(arr[:6])

# 7
print(arr[5:13])

# 8
print(arr[-5:])

# 9
print(arr[::2])

# 10
print(arr[::-1])


1
20
8
[  1   2   3   4 100   6]
[ 6  7  8  9 10 11 12 13]
[16 17 18 19 20]
[  1   3 100   7   9  11  13  15  17  19]
[ 20  19  18  17  16  15  14  13  12  11  10   9   8   7   6 100   4   3
   2   1]


2D array

In [2]:
# 11
arr2 = np.arange(1, 13).reshape(3, 4)

# 12
print(arr2[1, 2])

# 13
print(arr2[0])

# 14
print(arr2[:, -1])

# 15
print(arr2[:2])

# 16
print(arr2[:, -2:])

# 17
print(arr2[1, 1:3])

# 18
print(arr2[:2, :2])

# 19
arr2[arr2 == 6] = 60

# 20
arr2[2] = 0


7
[1 2 3 4]
[ 4  8 12]
[[1 2 3 4]
 [5 6 7 8]]
[[ 3  4]
 [ 7  8]
 [11 12]]
[6 7]
[[1 2]
 [5 6]]


3D array

In [3]:
# 21
arr3 = np.arange(1, 25).reshape(2, 3, 4)

# 22
print(arr3[0])

# 23
print(arr3[0, 1, 2])

# 24
print(arr3[1])

# 25
print(arr3[0, :, :])

# 26
print(arr3[:, 0, :])

# 27
print(arr3[:, :, -1])

# 28
arr3[0, 0, 0] = 999

# 29
arr3[arr3 > 15] = 0

# 30
print(arr3[:, :2, :2])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [13 14 15 16]]
[[ 4  8 12]
 [16 20 24]]
[[[ 0  2]
  [ 5  6]]

 [[13 14]
  [ 0  0]]]
