Task:1 Create a NumPy array with numbers from 1 to 10.

In [ ]:
import numpy as np
arr=np.array((1,2,3,4,5,6,7,8,9,10))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


Task:2 Create a 3×3 matrix filled with zeros.

In [ ]:
arr= np.array([[[0,0,0],[0,0,0],[0,0,0]]])
print(arr)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]]


Task:3 Create a 2×4 array filled with ones.

In [ ]:
arr= np.array([[1,1,1,1],[1,1,1,1]])
print(arr)

[[1 1 1 1]
 [1 1 1 1]]


Task:4 Generate 5 random integers between 10 and 50.

In [14]:
import random
import numpy

arr=np.random.randint(0,51,5)
print(arr)

[45 45 26 25 15]


Task:5 Find the shape, size, and datatype of an array.

In [15]:
import numpy

arr= np.array((1,2,3,4,5,6,7,8,9.10,11,12))

print(arr.shape)
print(arr.size)
print(arr.dtype)

(11,)
11
float64


Task: 6 Reshape a 1D array of size 12 into a 3×4 matrix.

In [19]:
arr=np.array(([1,2,3],[4,5,6],[7,8,9],[10,11,12]))
print(arr.T)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


Task: 7 Extract the first 3 elements from an array.

In [18]:
arr= np.array((1,2,3,4,5,6,7,8,9,10))
print(arr[:3])

[1 2 3]


Task: 8 Replace all even numbers in an array with 0.

In [20]:
arr= np.array((1,2,3,4,5,6,7,8,9,10))
arr[arr % 2 == 0] = 0
print(arr)

[1 0 3 0 5 0 7 0 9 0]


Task: 9 Create an identity matrix of size 4×4.

In [21]:
arr= np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Task: 10 Convert a Python list into a NumPy array.

In [25]:
list= [1,2,3,4,5]
arr=np.array(list)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>
